import React from 'react';

class SearchBar extends React.Component{
  state = {term: '' }

  onFormSubmit = (event) => {
    event.preventDefault();

    this.props.onSubmit(this.state.term)
  }

  randomBtn = () => {
    // let result
    const randomWord=[
      'movies',
      'sports',
      'news',
      'scotland',
      'cars',
      'internet',
      'hobbies',
      'cool',
      'software',
    ]
    
    function getRandomIndex(items) {
      return Math.floor(Math.random() * items.length);
    }

    function getRandomCategorie(){
      const randomIndex = getRandomIndex(randomWord)
      return randomWord[randomIndex]
      
    }
    const autoGeneratedResult = getRandomCategorie()
    this.props.onSubmit(autoGeneratedResult);

    this.setState({
      term: autoGeneratedResult
    });
  }

  render(){
    return(
      <div className="ui segment ">
        <form onSubmit={this.onFormSubmit} className="ui form">
          <div className="field">
            <label>Image Search</label>
            <input 
            type="text" 
            value={this.state.term}
            onChange={(e)=>{this.setState({term: e.target.value})}}
            />
          </div>
        </form>
        <button onClick={this.randomBtn} className="ui primary button btn-styles ">Random Categorie</button>
    </div>
    ) 
  }
}

export default SearchBar